service: aws-waf-logger

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-1
  memorySize: 3008
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: 'arn:aws:s3:::${self:provider.environment.LOG_BUCKET}/*'
    - Effect: Allow
      Action:
        - waf:*
        - waf-regional:*
        - logs:*
      Resource: '*'
  environment: ${file(./env.yml)}

package:
  exclude:
    - env.yml
    - env.yml.example
    - README.md
    - package.json

functions:
  log:
    handler: handler.log
    events:
      - schedule:
          rate: rate(${self:provider.environment.CHECK_EVERY_MINUTES} minutes)

resources:
  Conditions:
    CreateS3Resources: 
      Fn::Equals:
        - ${self:provider.environment.S3_ENABLE}
        - 'true'
    CreateLGResources: 
      Fn::Equals:
        - ${self:provider.environment.CLOUDWATCH_ENABLE}
        - 'true'
  Resources:
    Resources:
      Type: AWS::S3::Bucket
      Condition: CreateS3Resources
      Properties:
        BucketName: ${self:provider.environment.LOG_BUCKET}
        LifecycleConfiguration:
          Rules:
            - Id: WafLogsRetentionPolicy
              ExpirationInDays: ${self:provider.environment.RETENTION}
              Status: Enabled
    WAFLogGroup:
      Type: AWS::Logs::LogGroup
      Condition: CreateLGResources      
      Properties:
        LogGroupName: ${self:provider.environment.LOG_GROUP}
        RetentionInDays: ${self:provider.environment.RETENTION}